In [1]:
import argparse
import os
from glob import glob

import numpy as np

import robosuite as suite 

In [2]:
def collect_random_trajectory(env, timesteps=1000):
    """Run a random policy to collect trajectories."""
    
    env.reset()
    dof = env.action_dim

    actions = []

    for t in range(timesteps):
        action = np.random.randn(dof)
        actions.append(action)
        env.step(action)
        env.render()
        if t % 100 == 0:
            print(t)
    
    return actions

In [3]:
parser = argparse.ArgumentParser()
parser.add_argument("--environment", type=str, default="Lift")
parser.add_argument("--robots", nargs="+", type=str, default="Sawyer", help="Which robot(s) to use in the env")
parser.add_argument("--directory", type=str, default="/tmp/")
parser.add_argument("--timesteps", type=int, default=1000)
args = parser.parse_args([])

In [4]:
# create original environment
env = suite.make(
    args.environment,
    robots=args.robots,
    ignore_done=True,
    use_camera_obs=False,
    has_renderer=True,
    has_offscreen_renderer=False,
    control_freq=20,
)


# env = suite.make(
#     args.environment,
#     robots=args.robots,
#     ignore_done=True,
#     use_camera_obs=False,
#     has_renderer=False,
#     has_offscreen_renderer=True,
#     control_freq=20,
# )

In [5]:
print("Collecting some random data...")
actions=collect_random_trajectory(env, timesteps=100)

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/ns/miniconda3/envs/robosuite/lib/python3.8/site-packages/cv2/qt/plugins"


0


In [8]:
# action.shape

In [66]:
# env.reset() 

action=np.zeros(8)
for i in range(100):
    action[0] = -0.05
    # action[1]  =0.01
    env.step(action)
    env.render()

In [6]:
env.close()

In [7]:
#playing back the data

env.reset() 
for action in actions: 
    env.step(action)
    env.render()

In [8]:
env.close()

In [17]:
# actioncreate original environment
env = suite.make(
    args.environment,
    robots=args.robots,
    ignore_done=True,
    use_camera_obs=False,
    has_renderer=True,
    has_offscreen_renderer=False,
    control_freq=20,
)

array([ 0.23324412,  1.73055519, -0.02739413,  0.88585493,  0.55492683,
       -0.6452703 , -0.94016989, -0.65802031])

In [51]:
actions[:4]

[array([-0.242,  1.297,  1.938, -0.662,  0.441,  0.06 ,  0.461,  0.977]),
 array([ 0.699, -0.229, -1.138, -0.076,  0.438,  0.209,  0.532, -0.654]),
 array([ 0.636,  1.273,  0.108, -2.385,  2.746,  0.742, -1.13 ,  1.573]),
 array([ 0.843, -0.172, -0.933, -0.846, -1.415,  0.131, -0.722,  0.781])]

In [9]:
fn='/home/ns/wreg/matlab/sawyer_experiments/jps.csv'
fn='/home/ns/wreg/matlab/sawyer_experiments/jps3.csv' #coke grab


#read csv using numpy
import numpy as np
data=np.genfromtxt(fn,delimiter=',',skip_header=1)
data.shape

FileNotFoundError: /home/ns/wreg/matlab/sawyer_experiments/jps3.csv not found.

In [12]:
trajs=data[:,:8]
trajs.shape

(83, 8)

In [22]:
env.reset() 
for action in trajs:
    env.step(action)
    env.render()

In [16]:
action.shape

(8,)

In [10]:
env.close()

In [50]:
trajs[0]

array([-1.119,  0.701,  0.492, -2.114,  1.282, -0.963, -1.887, -3.381])

In [49]:
trajs[:5]

array([[-1.119,  0.701,  0.492, -2.114,  1.282, -0.963, -1.887, -3.381],
       [-1.119,  0.702,  0.51 , -2.109,  1.282, -0.944, -1.88 , -3.381],
       [-1.119,  0.703,  0.518, -2.099,  1.282, -0.931, -1.865, -3.381],
       [-1.119,  0.704,  0.539, -2.088,  1.278, -0.921, -1.861, -3.382],
       [-1.119,  0.703,  0.552, -2.073,  1.26 , -0.923, -1.861, -3.381]])

### playing with the joints

In [18]:
action

array([ 0.23324412,  1.73055519, -0.02739413,  0.88585493,  0.55492683,
       -0.6452703 , -0.94016989, -0.65802031])

In [25]:
env.reset()
env.render()

In [38]:
env.reset() 
# env.step(action)
for i in range(100):
    # action[1]=0.001
    # env.step(action)
    env.render()

In [20]:
env.close()

In [31]:
action=actions[0]

In [42]:
np.set_printoptions(precision=3)

In [45]:
act0=trajs[0]
for act in trajs[1:]:
    da=act-act0
    print(da) 
    act0=act
    env.step(da)
    env.render()
    

[0.    0.001 0.018 0.006 0.    0.019 0.007 0.   ]
[ 0.     0.001  0.009  0.01   0.     0.013  0.016 -0.   ]
[ 0.     0.001  0.021  0.011 -0.003  0.01   0.004 -0.   ]
[ 0.    -0.001  0.013  0.015 -0.019 -0.002  0.     0.001]
[ 0.    -0.007 -0.018  0.002 -0.01  -0.003 -0.007 -0.   ]
[ 0.    -0.005 -0.017  0.    -0.012 -0.017 -0.001  0.   ]
[ 0.    -0.005 -0.018  0.    -0.014 -0.026 -0.005  0.   ]
[ 0.    -0.004 -0.024  0.001 -0.015 -0.02  -0.002  0.   ]
[ 0.    -0.002 -0.014  0.    -0.008 -0.016 -0.     0.   ]
[ 0.    -0.001 -0.013  0.001 -0.007 -0.015 -0.001  0.   ]
[ 0.    -0.001 -0.016  0.002 -0.009 -0.017 -0.006  0.   ]
[ 0.    -0.001 -0.013  0.002 -0.008 -0.015 -0.009  0.   ]
[ 0.    -0.001 -0.027  0.003 -0.011 -0.026 -0.013  0.   ]
[ 0.    -0.    -0.015  0.001 -0.004 -0.015 -0.004 -0.   ]
[ 0.    -0.001 -0.017  0.    -0.003 -0.014 -0.001  0.   ]
[ 0.    -0.001 -0.027  0.    -0.005 -0.008 -0.001  0.   ]
[ 0.     0.    -0.024  0.    -0.003 -0.016 -0.014  0.   ]
[ 0.     0.    -0.033 

In [46]:
env.close()

In [40]:
da

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
trajs[0]

array([-1.119,  0.701,  0.492, -2.114,  1.282, -0.963, -1.887, -3.381])

trajs[-1]

In [48]:
trajs[-1]

array([-1.119,  0.673,  0.22 , -2.061,  1.15 , -1.191, -1.944, -3.381])

In [21]:
env = suite.make(
    args.environment,
    robots=args.robots,
    ignore_done=True,
    use_camera_obs=True,
    has_renderer=False,
    has_offscreen_renderer=True,
    render_camera="frontview",
    control_freq=20,
)

In [5]:
import imageio

In [6]:
obs = env.reset()
obs.keys()

odict_keys(['robot0_joint_pos_cos', 'robot0_joint_pos_sin', 'robot0_joint_vel', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', 'robot0_gripper_qvel', 'agentview_image', 'cube_pos', 'cube_quat', 'gripper_to_cube_pos', 'robot0_proprio-state', 'object-state'])

In [10]:
trajs[0]

array([-1.1188 ,  0.70109,  0.49193, -2.1141 ,  1.2817 , -0.96258,
       -1.8872 , -3.3815 ])

In [11]:
env.robots[0].set_robot_joint_positions(trajs[0][1:])

In [15]:
ndim = env.action_dim

# create a video writer with imageio
writer = imageio.get_writer("ok.mp4", fps=20)

frames = []
# for i in range(100):
#     action = 0.5 * np.random.randn(ndim)

for action in trajs:
    env.robots[0].set_robot_joint_positions(action[1:])

    # frame = obs["agentview" + "_image"]
    frame=env.render(mode="rgb_array", height=512, width=512, camera_name="frontview")
    writer.append_data(frame)  

writer.close()

TypeError: render() got an unexpected keyword argument 'height'

In [16]:
env.render()

AttributeError: 'NoneType' object has no attribute 'render'

In [30]:
len(trajs)

63

In [19]:
obs.keys()

odict_keys(['robot0_joint_pos_cos', 'robot0_joint_pos_sin', 'robot0_joint_vel', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', 'robot0_gripper_qvel', 'agentview_image', 'cube_pos', 'cube_quat', 'gripper_to_cube_pos', 'robot0_proprio-state', 'object-state'])

In [21]:
env.robots[0]._joint_positions

array([-0.10394849, -1.24053453,  0.00801046,  2.16060058, -0.00855128,
        0.52680617,  3.30082113])

In [23]:
env.robots[0].set_robot_joint_positions(env.robots[0]._joint_positions)